### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by superjanek321** [Kruithne/where-in-warcraft#1]
I have some troubles understanding how this code works, could you add some documentation?
Laso I've a question Is this final build, visible on the website?

**Comment by Kruithne** [comment]
Unfortunately I don't have the time to add any documentation to this project; the code is provided here as-is for reference. Unless I am mistaken, I'm pretty sure this repository reflects the most up-to-date version available on the website.

**Comment by superjanek321** [comment]
Ok, thanks for reply. I've got only few questions about this project. I will somehow eventually figure out how to add panorama to this project but I need anwear How can I add custom map for this project? and If You can answer me, Is the extension .scss and reference in the code .css fine or I need to change it?
And if you have time, What files do I need to add to get this working. I guess locations.json and panorama .jpg files with names for example "Frostwhisper Gorge" to image folder, right?
